history: 100
# list of devices
ratwheel:
 deviceId: 'ratwheel'
 diameter: 2.1

armwheel:
 deviceId: 'armwheel'
 diameter: 0.65

testwheel:
 deviceId: 'testwheel'
 diameter: 1

# cheer bot experiment
cheerbot:
 enabled: true
 minDelay: 5
 maxDelay: 10
 burstInterval: 5
 conditions:
  probabilities: ['none', 'low', 'viral']
  low:
   minCheers: 2
   maxCheers: 5
  viral:
   minCheers: 10
   maxCheers: 30 